### ISSUE TITLE
q ibc-transfer denom-trace {denom} should allow denom to begin with ibc

### ISSUE THREAD

**Issue by ValarDragon** [cosmos/ibc-go#1489]
The CLI command for `osmosisd q ibc-transfer denom-trace {denom}` do not accept the `ibc` prefix.

The natural UX of copy/pasting an IBC denom and querying it does not work as a consequence, e.g. copying `ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2` yields:

```
osmosisd q ibc-transfer denom-trace ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2
Error: rpc error: code = InvalidArgument desc = rpc error: code = InvalidArgument desc = invalid denom trace hash ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2, encoding/hex: invalid byte: U+0069 'i': invalid request
```

Instead one has to manually edit, to get 
```
osmosisd q ibc-transfer denom-trace 27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2
denom_trace:
  base_denom: uatom
  path: transfer/channel-0
```

## Summary of Bug

`q ibc-transfer denom-trace` should accept ibc prefixes

## Version

IBC v2.x

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned
