### ISSUE TITLE
Introduce `buf generate` to generate *.proto to *.pb.go

### ISSUE THREAD

**Issue by liangping** [cosmos/ibc-go#1904]
## Summary

Currently, we have introduced `buf` to manage protobuf stuffs in IBC-go repo. we can enable `buf generate` by simply adding `buf.gen.yaml` . and it would be more friendly to developers than running a script in a docker container.

## Problem Definition

It's complicated to generate new *.proto to go files. 

The current approach is :

1. Install docker
2. Download the tendermint-dev image.
3. `make proto-gen `- ( run `./scripts/protoc-gen.sh` in docker container.) 
4. Copy *.pb.go to destination directory.

## Proposal

The new approach would be:

1. Install `buf`
2. Add config for generation (only once)
3. Run `buf generate`

**Note** : the biggest difference is that the newly approach would use latest version `protoc`, which generate pointer for none-primitive types.  Here is the sample

```go
// GenesisState defines the interchain accounts genesis state
type GenesisState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

        // generated by current approach
	//ControllerGenesisState ControllerGenesisState `protobuf:"bytes,1,opt,name=controller_genesis_state,json=controllerGenesisState,proto3" json:"controller_genesis_state,omitempty"`
	//HostGenesisState       HostGenesisState       `protobuf:"bytes,2,opt,name=host_genesis_state,json=hostGenesisState,proto3" json:"host_genesis_state,omitempty"`

        // generated by `buf generate`
	ControllerGenesisState *ControllerGenesisState `protobuf:"bytes,1,opt,name=controller_genesis_state,json=controllerGenesisState,proto3" json:"controller_genesis_state,omitempty"`
	HostGenesisState       *HostGenesisState       `protobuf:"bytes,2,opt,name=host_genesis_state,json=hostGenesisState,proto3" json:"host_genesis_state,omitempty"`
}
```

buf.gen.yaml:

```yaml
version: v1
plugins:
  - name: go
    out: gen/proto/go
    opt: 
      - experimental_allow_proto3_optional=true
  - name: go-grpc
    out: gen/proto/go
    opt:
      - paths=source_relative
      - require_unimplemented_servers=false
      - experimental_allow_proto3_optional=true
```

if this proposal is accepted, I would like push a PR.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by liangping** [comment]
I would like suggest to make this change from v5.

**Comment by liangping** [comment]
if we use plugin `gogofaster`, we can get less pointer types for fieds.
```yaml
version: v1
plugins:
  - name: gogofaster
    out: gen/proto/go
    opt: 
      - Mgoogle/protobuf/timestamp.proto=github.com/gogo/protobuf/types
      - Mgoogle/protobuf/duration.proto=github.com/golang/protobuf/ptypes/duration
      - plugins=grpc
```

Here is sample:
```go
// GenesisState defines the interchain accounts genesis state
type GenesisState struct {
	ControllerGenesisState ControllerGenesisState `protobuf:"bytes,1,opt,name=controller_genesis_state,json=controllerGenesisState,proto3" json:"controller_genesis_state" yaml:"controller_genesis_state"`
	HostGenesisState       HostGenesisState       `protobuf:"bytes,2,opt,name=host_genesis_state,json=hostGenesisState,proto3" json:"host_genesis_state" yaml:"host_genesis_state"`
}
```
