### ISSUE TITLE
Allow specification of arbitrary values when running E2E tests

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#2513]
## Summary

Currently, in our E2E tests, we have drop down lists of the possible tags that we can use.

An example of how these dropdown lists are defined can be found [here](https://github.com/cosmos/ibc-go/blob/8c7c6559c9c075a969485ccd3d008022aa863f1c/.github/workflows/e2e-manual-icad.yaml#L20-L29)

This is perfectly fine when we want to run tests on released images, but the flow for adding new entries to this for testing purposes (e.g. using an image from a PR instead of an existing tag ) is not smooth. In order to do this, I would need to.

1. Change the workflow file in a branch to hard code a new value (`pr-1234`)
2. Run the workflow from the UI selecting the development branch. ( `pr-1234` would now be in the drop down list)

I propose the following solution. 

Maintain the dropdown list and extend as appropriate with released versions, but also add an **optional** text field for each value that is configurable via the UI. If specified, the value will take precedence. This allows our existing workflows to support arbitrary images and tags, while also providing a nice UX in the form of dropdown list.

This would look something like

```yaml
on:
  workflow_dispatch:
    inputs:
      chain-a-tag:
        description: 'The tag to use for chain A'
        required: true
        type: choice
        default: master
        options:
          - master
          - v0.3.4
          - v0.2.3
          - v0.1.4
      chain-a-tag-override:
        description: 'The custom tag for chain A'
        required: false
        type: string
        default: ""
```

And then where the value is used

```yaml
jobs:
  e2e-manual:
    uses: ./.github/workflows/e2e-test-workflow-call.yml
    with:
      chain-a-tag: "${{ github.event.inputs.chain-a-tag-override || github.event.inputs.chain-a-tag }}"
```

Note: I didn't test this syntax, I believe it should work or be similar to what we need.

This will add a little bit of clutter (maybe all the override fields can go to the bottom) but it gives us full flexibility with our workflows.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned
