### ISSUE TITLE
Add a link checker to CI

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#253]
## Summary

It'd be nice to know which links are broken via a link checker

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
Add
```
name: Check Markdown links
on: [push, pull_request]
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
```

 to .github/workflows/link-check.yml
