### ISSUE TITLE
Tweak config file to allow easy toggling of relayers

### ISSUE THREAD

**Issue by DimitrisJim** [cosmos/ibc-go#3981]
## Summary of Bug

I discussed this with Cian in the past and this https://github.com/cosmos/ibc-go/actions/runs/5407017716 brought it to my attention again. The failure in the e2e workflow for hermes stems from the fact that the config file holds configuration only for rly and the tag that the run is attempting to run is 'latest' instead of '1.4.0'.

To make it easier to switch between relayers we could have a single environment variable (i.e `ACTIVE_RELAYER`) that we can use to switch between them, a rough sketch up thought up in the past was:

```yaml
relayers:
  activeRelayer:  # ACTIVE_RELAYER 
  configurations:
  - relayer: hermes
    image: ghcr.io/informalsystems/hermes:1.4.0
    tag: 1.4.0
  - relayer: rly
    id: rly # override with RELAYER_TYPE
    image: damiannolan/rly # override with RELAYER_IMAGE
    tag: latest # override with RELAYER_TAG
```

this way, we should be able to easily switch between them using a single environment variable.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned
