### ISSUE TITLE
Workflow does not fail even if exit code 1

### ISSUE THREAD

**Issue by anhductn2001** [cosmos/ibc-go#5190]
## Summary of Bug

When I ran CI in my dev process found that build_test_matrix flow was not failing even if exit code = 1

More context [here](https://github.com/vuong177/ibc-go/actions/runs/7021188046/job/19102656110) 

```
Run echo "matrix=$(go run cmd/build_test_matrix/main.go)" >> $GITHUB_OUTPUT
  echo "matrix=$(go run cmd/build_test_matrix/main.go)" >> $GITHUB_OUTPUT
  shell: /usr/bin/bash -e {0}
  env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ibc-go-simd
    IMAGE_NAME_WASM: ibc-go-wasm-simd
    TEST_ENTRYPOINT: 
    TEST_EXCLUSIONS: TestUpgradeTestSuite,TestGrandpaTestSuite
    TEST_NAME: 
exit status 1
```

## Expected Behaviour

Causes this step to throw an error when the exit code is different from 0

## Version

On **main** branch

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned
