### ISSUE TITLE
e2e: Group tests better for easy developer onboarding

### ISSUE THREAD

**Issue by DeshErBojhaa** [cosmos/ibc-go#8363]
We can consider running/exposing a subset of tests from the Makefile. 

Upgrade e2e tests require extra setup in `ibc-go-e2e-config.yaml`. Which is not obvious for someone new to the repo. Also upgrade tests are excluded in the default CI workflow.

```yaml
jobs:
  e2e:
    with:
      test-exclusions: 'TestUpgradeTestSuite,TestTransferTestSuite,TestAuthzTransferTestSuite,TestTransferTestSuiteSendReceive,TestTransferTestSuiteSendEnabled,TestTransferLocalhostTestSuite,TestConnectionTestSuite,TestInterchainAccountsGovTestSuite'
```

Given all this, we should figure out how to organize/grop tests for a better developer obboarding.

Possible considerations:
- More clear documentation
- More explicit fail msg
- New make command that only shows the `functionality` tests. And another make command that shows all tests.
